name: CI
on: [push, pull_request]
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: '3.10'
      - name: Install deps & run tests
        run: |
          cd api-tests
          pip install -r requirements.txt
          pytest -q

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: node-version: '18'
      - run: |
          cd e2e-tests
          npm ci
          npx playwright install --with-deps
          npx playwright test --reporter=github
